#esqueleto del workflow/pipeline de mi proyecto

name: Mi Primera Integracion Continua

on: push


jobs:
  build: #esto es el nombre que cada uno le ponga, no es ningun termino de yaml, ni github ni nada
    runs-on: ubuntu-latest
    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v2

      - name: Instalar JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"

      - name: Construir con Maven
        run: mvn clean package -DskipTests
        run: ls target/

      - name: Guardar paquete .jar para despues desplegar
        uses: actions/upload-artifact@v4
        with:
          name: moviecards-java
          path: "${{ github.workspace }}/target/*.jar"


  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: pruebas
        run: echo "pruebas"


  controlar_calidad:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: calidad
        run: echo "calidad"


  deploy:
    needs: controlar_calidad
    runs-on: ubuntu-latest
    steps:
      - name: despliegue
        run: echo "despliegue"